name: pinput_example
version: 1.0.0+1
publish_to: "none"
description: "PinPut Example"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  pinput:
    path: ../
  smart_auth: ^3.2.0
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
