name: flutter_pinput
version: 1.0.1
description: "Pin code input (OTP) text field, iOS SMS autofill, Android SMS autofill One Time Code, Password, Passcode, Captcha, Security, Coupon, Wowcher, 2FA, Two step verification"
homepage: https://github.com/SunnatilloShavkatov/flutter_pinput.git
repository: https://github.com/SunnatilloShavkatov/flutter_pinput.git
issue_tracker: https://github.com/SunnatilloShavkatov/flutter_pinput.gitissues
topics:
  - otp
  - pin-input
  - pin-code
  - passcode
  - sms-autofill

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  analysis_lints: ^1.0.5